{% set version = '4022.85' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fcopulae
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fCopulae_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fCopulae/fCopulae_{{ version }}.tar.gz
  sha256: 02bfca9b6953e306961b5578c5fdb06a6373255c34c3dcbdf4a2725204a4f2a1

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-fbasics
    - r-fmultivar
    - r-timedate
    - r-timeseries
  run:
    - r-base
    - r-fbasics
    - r-fmultivar
    - r-timedate
    - r-timeseries

test:
  commands:
    - $R -e "library('fCopulae')"           # [not win]
    - "\"%R%\" -e \"library('fCopulae')\""  # [win]

about:
  home: https://www.rmetrics.org
  license: GPL-2.0-or-later
  summary: Provides a  collection of functions to manage, to investigate and to analyze bivariate
    financial returns by Copulae. Included are the families of Archemedean, Elliptical,
    Extreme Value, and Empirical Copulae.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - janjagusch


# Package: fCopulae
# Title: Rmetrics - Bivariate Dependence Structures with Copulae
# Date: 2023-01-03
# Version: 4022.85
# Author: Diethelm Wuertz [aut], Tobias Setz [aut], Yohan Chalabi [ctb], Paul Smith [cre]
# Maintainer: Paul Smith <paul@waternumbers.co.uk>
# Description: Provides a  collection of functions to manage, to investigate and to analyze bivariate financial returns by Copulae. Included are the families of Archemedean, Elliptical, Extreme Value, and Empirical Copulae.
# Depends: R (>= 2.15.1), timeDate, timeSeries, fBasics, fMultivar
# Imports: grDevices, graphics, stats
# Suggests: methods, RUnit, tcltk, mvtnorm, sn
# License: GPL (>= 2)
# URL: https://www.rmetrics.org
# NeedsCompilation: no
# Packaged: 2023-01-07 20:15:28 UTC; paul
# Repository: CRAN
# Date/Publication: 2023-01-07 22:50:11 UTC
